using System.IO;

namespace Currycomb.Common.Network.Game.Packets
{
    [GamePacket(GamePacketId.ServerEncryption)]
    public readonly struct PacketEncryptionResponse : IGamePacket
    {
        public readonly byte[] SharedSecret; // The AES secret.
        public readonly byte[] VerifyToken;  // A sequence of random bytes generated by the server. Always 4 for Notchian servers.

        public PacketEncryptionResponse(BinaryReader reader)
        {
            SharedSecret = reader.ReadBytes(reader.Read7BitEncodedInt());
            VerifyToken = reader.ReadBytes(reader.Read7BitEncodedInt());
        }

        public void Write(BinaryWriter writer)
        {
            writer.Write7BitEncodedInt(SharedSecret.Length);
            writer.Write(SharedSecret);
            writer.Write7BitEncodedInt(VerifyToken.Length);
            writer.Write(VerifyToken);
        }
    }
}
